### ISSUE TITLE
Argument Null Refference - Restarting

### ISSUE THREAD

**Issue by 1461748123** [shiftcodeYT/PokeBot2#23] opened 2016-07-23 08:43 UTC
After running the bot for about 2 hours, this error

> Argument Null Refference - Restarting

shows up and the bot wont restart.
The only way to fix it is to delete all the files and relogin.
![image](https://cloud.githubusercontent.com/assets/6280864/17077039/e9fb5f3e-5076-11e6-9b01-1617ea047602.png)

**Comment by shiftcodeYT** [comment] 2016-07-23 08:48
Dupe of #13

**Closed by shiftcodeYT** 2016-07-23 08:48 UTC
Labels: duplicate, fixed
